---
title: "Visulization_2"
author: "Ruby"
date: "2023-12-30"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


##load package
```{r}
library(ggplot2)
library(dplyr)
library(car)
library(mfp)
library(lspline)
library(rms)
```

##read data
```{r}
dt <- read.csv("../clean/clean_dt.csv")
```

```{r}
dt$bmi <- 0
dt[dt$BMXBMI >= 25, "bmi"] <- 1
table(dt$bmi)
hist(dt$FFQ0102)
```
```{r}
topval <- 11

themedian <- c()
oddslist <- c()
poscount <- c()
negcount <- c()

for (j in 1:topval) {
  temp_median <- mean(dt$FFQ0102[dt$FFQ0102==j])
  
  temp_pos <- nrow(dt[dt$FFQ0102==j & dt$bmi==1, ])
  
  temp_neg <- nrow(dt[dt$FFQ0102==j & dt$bmi==0, ])
  
  temp_prob <- mean(dt$bmi[dt$FFQ0102==j])
  temp_odds <- temp_prob/(1-temp_prob)
  themedian <- c(themedian, temp_median)
  poscount <- c(poscount, temp_pos)
  negcount <- c(negcount, temp_neg)
  oddslist <- c(oddslist, temp_odds)
}


lci_odds <- oddslist / (exp(qnorm(0.975)*sqrt(1/poscount)+(1/negcount)))
uci_odds <- oddslist * (exp(qnorm(0.975)*sqrt(1/poscount)+(1/negcount)))

grp_102 <- seq(1, topval, by = 1)
obsdata <- cbind(grp_102, themedian, negcount, poscount, oddslist, lci_odds, uci_odds)
obsdata <- data.frame(obsdata)

ggplot() +
  geom_pointrange(data = obsdata, mapping = aes(x = themedian, y = oddslist, ymin = lci_odds, ymax = uci_odds)) +
  scale_y_continuous(trans = 'log', limits = c(min(obsdata$lci_odds), max(obsdata$uci_odds))) +
  ggtitle("Odds (along with 95% CI) of the BMI within each of the potato chips cosumption group")

```


```{r}
#linear model
model_linear <- glm(bmi~FFQ0102, data = dt, family = binomial(link = "logit"))
summary(model_linear)
exp(cbind(coef(model_linear), confint(model_linear)))
```

```{r}
dt$linpred_logodds <- predict(model_linear)
dt$linpred_odds <- exp(dt$linpred_logodds)

ggplot() +
  geom_pointrange(data = obsdata, mapping = aes(x=themedian, y=oddslist, ymin=lci_odds, ymax=uci_odds)) +
  scale_y_continuous(trans = 'log', limits = c(min(obsdata$lci_odds), max(obsdata$uci_odds))) +
  geom_line(data = dt, aes(x=FFQ0102, y=linpred_odds, color="Linear"), color="blue") +
  xlab("Frequency of eating potato chips") +
  ylab("odds of bmi")
```



```{r}
dt$FFQ0102_sq <- dt$FFQ0102^2

model_quad <- glm(bmi~FFQ0102 + FFQ0102_sq, data = dt, family = binomial(link = "logit"))
summary(model_quad)
exp(cbind(coef(model_quad), confint(model_quad)))
```

```{r}
dt$quadpred_logodds <- predict(model_quad)
dt$quadpred_odds <- exp(dt$quadpred_logodds)


ggplot() +
  geom_pointrange(data = obsdata, mapping = aes(x=themedian, y=oddslist, ymin=lci_odds, ymax=uci_odds)) +
  scale_y_continuous(trans = 'log', limits = c(min(obsdata$lci_odds), max(obsdata$uci_odds))) +
  geom_line(data = dt, aes(x=FFQ0102, y=linpred_odds, color="Linear"), color="blue") +
  geom_line(data = dt, aes(x=FFQ0102, y=quadpred_odds, color="Quadratic"), color="red") +
  xlab("Frequency of eating potato chips") +
  ylab("odds of bmi")
```

```{r}
#frctional polynomial
model_fp <- mfp(bmi~fp(FFQ0102, df=4, select=0.05), family = binomial, data = dt)
summary(model_fp)
```

```{r}
dt$fp_pred <- exp(predict(model_fp))
colors1 <- c("Linear" = "blue", "Quadratic" = "red", "FP" = "green")

ggplot() +
  geom_pointrange(data = obsdata, mapping = aes(x=themedian, y=oddslist, ymin=lci_odds, ymax=uci_odds)) +
  scale_y_continuous(trans = 'log', limits = c(min(obsdata$lci_odds), max(obsdata$uci_odds))) +
  geom_line(data = dt, aes(x=FFQ0102, y=linpred_odds, color="Linear")) +
  geom_line(data = dt, aes(x=FFQ0102, y=quadpred_odds, color="Quadratic")) +
  geom_line(data = dt, aes(x=FFQ0102, y=fp_pred, color = "FP")) +
  xlab("Frequency of eating potato chips") +
  ylab("odds of PIR") +
  scale_color_manual(values = colors1)
```

```{r}
model_linsp <- glm(bmi~lspline(FFQ0102, knots =c(2,10)), family = binomial, data = dt)
summary(model_linsp)
```

```{r}
dt$linsp_pred <- exp(predict(model_linsp))


colors1 <- c("Linear" = "lightblue2", "Quadratic" = "yellow3", "FP" = "green4", "Linearspline" = "pink2")

ggplot() +
  geom_pointrange(data = obsdata, mapping = aes(x=themedian, y=oddslist, ymin=lci_odds, ymax=uci_odds)) +
  scale_y_continuous(trans = 'log', limits = c(min(obsdata$lci_odds), max(obsdata$uci_odds))) +
  geom_line(data = dt, aes(x=FFQ0102, y=linpred_odds, color="Linear")) +
  geom_line(data = dt, aes(x=FFQ0102, y=quadpred_odds, color="Quadratic")) +
  geom_line(data = dt, aes(x=FFQ0102, y=fp_pred, color = "FP")) +
  geom_line(data = dt, aes(x=FFQ0102, y=linsp_pred, color = "Linearspline")) +
  xlab("Frequency of eating potato chips") +
  ylab("odds of bmi") +
  scale_color_manual(values = colors1)
```

```{r}
model_cubicsp <- glm(bmi~rcs(FFQ0102, knots = c(2, 9, 10)), family = binomial, data = dt)

dt$cubicsp_pred <- exp(predict(model_cubicsp))


colors1 <- c("Linear" = "blue", "Quadratic" = "yellow3", "FP" = "red", "Linearspline" = "pink2", "cubic_spline" = "green3")

ggplot() +
  geom_pointrange(data = obsdata, mapping = aes(x=themedian, y=oddslist, ymin=lci_odds, ymax=uci_odds)) +
  scale_y_continuous(trans = 'log', limits = c(min(obsdata$lci_odds), max(obsdata$uci_odds))) +
  geom_line(data = dt, aes(x=FFQ0102, y=linpred_odds, color="Linear")) +
  geom_line(data = dt, aes(x=FFQ0102, y=quadpred_odds, color="Quadratic")) +
  geom_line(data = dt, aes(x=FFQ0102, y=fp_pred, color = "FP"), lty = 2) +
  geom_line(data = dt, aes(x=FFQ0102, y=linsp_pred, color = "Linearspline")) + geom_line(data = dt, aes(x=FFQ0102, y=cubicsp_pred, color = "cubic_spline")) +
  xlab("Frequency of eating potato chips") +
  ylab("odds of bmi") +
  scale_color_manual(values = colors1) +
  ggtitle("BMI Odds Ratio by Frequency of Potato Chip Consumption")
```

```{r}
AIC(model_linear)
AIC(model_quad)
AIC(model_fp)
AIC(model_linsp)
AIC(model_cubicsp)
BIC(model_linear)
BIC(model_quad)
BIC(model_fp)
BIC(model_linsp)
BIC(model_cubicsp)

```


```{r}
dt$PIR <- 0
dt[dt$INDFMPIR >= 2, "PIR"] <- 1
table(dt$PIR)

model_linear_pir <- glm(bmi~FFQ0102 + INDFMPIR, data = dt, family = binomial(link = "logit"))
summary(model_linear_pir)
```

```{r}
no_intmodel <- glm(bmi ~ as.factor(PIR) + as.factor(FFQ0102), family = binomial(link=logit), data = dt)
summary(no_intmodel)
exp(cbind(coef(no_intmodel)))
```

```{r}
intmodel <- glm(bmi ~ as.factor(PIR)*as.factor(FFQ0102), family = binomial(link = logit), data = dt)
summary(intmodel)
exp(cbind(coef(intmodel), coef(intmodel)))
```

```{r}
lrtest(no_intmodel, intmodel)
```
```{asis}
The results of the likelihood ratio test (p=0.638) suggest there is little evidence of an interaction between poverty income ratio and frequency of eating chips.
```

```{r}
dt$PIR_5 <- 0
dt[dt$INDFMPIR >= 1 & dt$INDFMPIR < 2, "PIR_5"] <- 1
dt[dt$INDFMPIR >= 2 & dt$INDFMPIR < 4, "PIR_5"] <- 2

dt[dt$INDFMPIR >= 4, "PIR_5"] <- 3



table(dt$PIR_5, dt$FFQ0102)
```


```{r}
write.csv(dt,"../clean/bmi_model_dt.csv", row.names = FALSE)
write.csv(obsdata, "../clean/bmi_odds_dt.csv", row.names = FALSE)
```